Stub
ZuevAlexey/pesta pull request #3
Opened 2021-03-09 11:57 UTC by ErmakFPG

Add stub

2021-03-09 14:15 UTC, ZuevAlexey requested changes

2021-03-09 14:15 UTC, ZuevAlexey commented on providers/advertProvider.py
> +    def get_advert():
get_adverts

2021-03-09 14:15 UTC, ZuevAlexey commented on providers/aggregator.py
> +        return self.providers.get_advert()
providers - это список провайдеров. Нужно итерировать по ним для получения общего результата

2021-03-09 14:15 UTC, ZuevAlexey commented on providers/avitoAdvertProvider.py
> +        return Advert(id=2079067725,
метод get_adverts возвращает список объявлений

2021-03-09 14:15 UTC, ZuevAlexey commented on providers/avitoAdvertProvider.py
> +    def get_advert():
get_adverts

2021-03-09 14:15 UTC, ZuevAlexey commented on providers/avitoAdvertProvider.py
> +        super().__init__(SourceType.AVITO.value)
на сколько я помню - просто SourceType.AVITO

2021-03-09 14:15 UTC, ZuevAlexey commented on providers/avitoAdvertProvider.py
> +                      source_type='Авито')
SourceType.AVITO. Мы для этого и вводили перечисление SourceType, чтобы его использовать, а не строковое представление

2021-03-09 14:15 UTC, ZuevAlexey commented on main.py
> +advert = Aggregator(AvitoAdvertProvider).get_adverts()
нужно передавать список провайдеров в конструктор аггрегатора

2021-03-09 14:15 UTC, ZuevAlexey commented on main.py
> +           advert.title, advert.url]:
Нужно формировать 1 сообщение для объявления, в котором будут все эти свойства, а не каждое свойство в новом сообщении

2021-03-10 07:10 UTC, ErmakFPG commented on providers/avitoAdvertProvider.py
> +                      source_type='Авито')
Поправил, но не очень понимаю необходимость использования SourceType.

2021-03-10 07:26 UTC, ZuevAlexey commented on providers/avitoAdvertProvider.py
> +                      source_type='Авито')
Как минимум ты не опечатаешься, т.к. ты используешь ссылку на значение, а не строковый литерал. И еще с тем значением, что ты написал никак не сопоставить какой Provider предоставил это объявление и например запросить его актуальное состояние напрямую с Provider по id. (возможно такой функционал будет необходим)

2021-03-10 08:16 UTC, ZuevAlexey requested changes

2021-03-10 08:16 UTC, ZuevAlexey commented on main.py
> +          f'{advert.description}\n\nСтоимость хаты: {advert.price} рублей\n\n{advert.title}\n{advert.url}\n'
Это плохо читаемо) сделай перенос в стиле \ для каждого свойства

2021-03-10 08:16 UTC, ZuevAlexey commented on providers/avitoAdvertProvider.py
> +                       source_type=SourceType.AVITO.value)]
Просто SourceType.AVITO, нам нужен именно ENUM, а не строка

2021-03-10 09:02 UTC, ZuevAlexey approved these changes

2021-03-10 09:02 UTC, merged